/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iclinic.views.patients;

import java.awt.Color;
import javax.swing.Icon;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author obiero
 */
public class PatientForm extends javax.swing.JDialog {

    /**
     * Creates new form AddPatient
     */
    public PatientForm(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        IconFontSwing.register(FontAwesome.getIconFont());
        this.setTitle(" Add Patient");
        initComponents();
    }
    
    public void clearForm()
    {
        jTextSurname.setText("");
        jTextFirstName.setText("");
        jTextDoB.setText("");
        jTextStdID.setText("");
        jTextNhif.setText("");
        
        jTextNextOfKin.setText("");
        jTextEmergencyNbr.setText("");
        jTextAddress.setText("");
        jTextCity.setText("");
        jTextMobile.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        jTextSurname = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFirstName = new javax.swing.JTextField();
        jComboTitle = new javax.swing.JComboBox<>();
        Icon iconBasicDetails = IconFontSwing.buildIcon(FontAwesome.USER_PLUS, 25, new Color(0, 150, 0));
        jLabelBasicDetails = new javax.swing.JLabel(iconBasicDetails);
        jLabel5 = new javax.swing.JLabel();
        Icon iconSave = IconFontSwing.buildIcon(FontAwesome.SMILE_O, 15, new Color(0, 150, 0));
        jButtonSave = new javax.swing.JButton(iconSave);
        jLabelDoB = new javax.swing.JLabel();
        jTextDoB = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jComboGender = new javax.swing.JComboBox<>();
        jLabelStdID = new javax.swing.JLabel();
        jTextStdID = new javax.swing.JTextField();
        jLabelNhif = new javax.swing.JLabel();
        jTextNhif = new javax.swing.JTextField();
        jLabelNextOfKin = new javax.swing.JLabel();
        jTextNextOfKin = new javax.swing.JTextField();
        jLabelEmergencyNbr = new javax.swing.JLabel();
        jTextEmergencyNbr = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jTextCity = new javax.swing.JTextField();
        jLabelCity = new javax.swing.JLabel();
        jTextMobile = new javax.swing.JTextField();
        jLabelMobile = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelSaveNotification = new javax.swing.JLabel();
        jButtonClearForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitle.setText("Title");

        jLabelSurname.setText("Surname");

        jTextSurname.setToolTipText("");

        jLabelFirstName.setText("First Name");

        jTextFirstName.setToolTipText("");
        jTextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstNameActionPerformed(evt);
            }
        });

        jComboTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mrs", "Master", "Miss", "Dr", "Prof" }));
        jComboTitle.setToolTipText("");
        jComboTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTitleActionPerformed(evt);
            }
        });

        jLabelBasicDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelBasicDetails.setForeground(new java.awt.Color(102, 102, 102));
        jLabelBasicDetails.setText("Basic details");
        jLabelBasicDetails.setToolTipText("Basic details");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Contact details");
        jLabel5.setToolTipText("Contact details");

        jButtonSave.setText("Save");
        jButtonSave.setToolTipText("Save patient");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelDoB.setText("Date of birth");

        jLabelGender.setText("Gender");

        jComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Not specified" }));
        jComboGender.setToolTipText("");
        jComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGenderActionPerformed(evt);
            }
        });

        jLabelStdID.setText("Student ID");

        jTextStdID.setToolTipText("");

        jLabelNhif.setText("NHIF");

        jLabelNextOfKin.setText("Next of kin name");

        jTextNextOfKin.setToolTipText("");

        jLabelEmergencyNbr.setText("Emergency phone");

        jTextEmergencyNbr.setToolTipText("");

        jLabelAddress.setText("Address");

        jTextAddress.setToolTipText("");

        jTextCity.setToolTipText("");

        jLabelCity.setText("City");

        jTextMobile.setToolTipText("");

        jLabelMobile.setText("Mobile");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelSaveNotification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSaveNotification.setMaximumSize(new java.awt.Dimension(500, 55));

        jButtonClearForm.setText("Clear form");
        jButtonClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(376, Short.MAX_VALUE)
                        .addComponent(jButtonClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSaveNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelBasicDetails)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSurname)
                                            .addComponent(jLabelTitle)
                                            .addComponent(jLabelFirstName)
                                            .addComponent(jLabelDoB)
                                            .addComponent(jLabelGender)
                                            .addComponent(jLabelStdID)
                                            .addComponent(jLabelNhif))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextSurname)
                                            .addComponent(jTextFirstName)
                                            .addComponent(jTextDoB)
                                            .addComponent(jTextStdID)
                                            .addComponent(jTextNhif)
                                            .addComponent(jComboGender, 0, 162, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmergencyNbr)
                                            .addComponent(jLabelNextOfKin)
                                            .addComponent(jLabelAddress)
                                            .addComponent(jLabelCity)
                                            .addComponent(jLabelMobile))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextEmergencyNbr, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(jTextNextOfKin)
                                            .addComponent(jTextAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(jTextCity, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(jTextMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBasicDetails)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboTitle)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSurname)
                            .addComponent(jTextSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDoB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGender)
                            .addComponent(jComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextStdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStdID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNhif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNhif)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNextOfKin)
                            .addComponent(jTextNextOfKin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmergencyNbr)
                            .addComponent(jTextEmergencyNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddress)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCity)
                            .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMobile)
                            .addComponent(jTextMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearForm)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabelSaveNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTitleActionPerformed

    private void jComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboGenderActionPerformed

    private void jTextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstNameActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Save();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFormActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonClearFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PatientForm dialog = new PatientForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void setSaveNotificationText(String m, Color color)
    {
        jLabelSaveNotification.setText(m);
        jLabelSaveNotification.setForeground(color);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearForm;
    private javax.swing.JButton jButtonSave;
    public javax.swing.JComboBox<String> jComboGender;
    public javax.swing.JComboBox<String> jComboTitle;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBasicDetails;
    public javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelDoB;
    public javax.swing.JLabel jLabelEmergencyNbr;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelNextOfKin;
    private javax.swing.JLabel jLabelNhif;
    private javax.swing.JLabel jLabelSaveNotification;
    private javax.swing.JLabel jLabelStdID;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jTextAddress;
    public javax.swing.JTextField jTextCity;
    public javax.swing.JTextField jTextDoB;
    public javax.swing.JTextField jTextEmergencyNbr;
    public javax.swing.JTextField jTextFirstName;
    public javax.swing.JTextField jTextMobile;
    public javax.swing.JTextField jTextNextOfKin;
    public javax.swing.JTextField jTextNhif;
    public javax.swing.JTextField jTextStdID;
    public javax.swing.JTextField jTextSurname;
    // End of variables declaration//GEN-END:variables
}
