/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iclinic.views;

import iclinic.views.patients.PatientForm;
import iclinic.views.patients.PatientSearchForm;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JLabel;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author obiero
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    public static PasswordDialog passDialog;
    public static PatientForm patientForm;
    public static PatientSearchForm patientSearchForm;
     
    public MainWindow() {
        
        patientForm = new PatientForm(this, true);
        patientForm.setLocationRelativeTo(this);
        patientForm.setVisible(false);
  
        patientSearchForm = new PatientSearchForm(this, true);
        patientSearchForm.setLocationRelativeTo(this);
        patientSearchForm.setVisible(false);
        
         
        passDialog = new PasswordDialog(this, true);
        passDialog.setVisible(true);
              
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jPatientMenu = new javax.swing.JMenu();
        jMenuAddPatient = new javax.swing.JMenuItem();
        jMenuAddVisit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPatientMenu.setText("Patient");

        jMenuAddPatient.setText("Add new");
        jMenuAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddPatientActionPerformed(evt);
            }
        });
        jPatientMenu.add(jMenuAddPatient);

        jMenuAddVisit.setText("Add Visit");
        jMenuAddVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAddVisitActionPerformed(evt);
            }
        });
        jPatientMenu.add(jMenuAddVisit);

        jMenuBar1.add(jPatientMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAddVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddVisitActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Search();
    }//GEN-LAST:event_jMenuAddVisitActionPerformed

    private void jMenuAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAddPatientActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Add();
    }//GEN-LAST:event_jMenuAddPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainWindow().setVisible(true);
            }
        });
    

    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuAddPatient;
    private javax.swing.JMenuItem jMenuAddVisit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jPatientMenu;
    // End of variables declaration//GEN-END:variables
}
