/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iclinic.views;

import iclinic.views.patients.PatientForm;
import iclinic.views.patients.PatientSearchForm;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JLabel;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author obiero
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    public static PasswordDialog passDialog;
    public static PatientForm patientForm;
    public static PatientSearchForm patientSearchForm;
     
    public MainWindow() {
        
        this.setTitle("Welcome to USIU iClinic");
        
        patientForm = new PatientForm(this, true);
        patientForm.setLocationRelativeTo(this);
        patientForm.setVisible(false);
  
        patientSearchForm = new PatientSearchForm(this, true);
        patientSearchForm.setLocationRelativeTo(this);
        patientSearchForm.setVisible(false);
        
         
        passDialog = new PasswordDialog(this, true);
        passDialog.setVisible(true);
              
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconFontSwing.register(FontAwesome.getIconFont());
        Icon icon = IconFontSwing.buildIcon(FontAwesome.USER, 24, new Color(0, 150, 0));
        jButtonRegisterPatient = new javax.swing.JButton(icon);
        IconFontSwing.register(FontAwesome.getIconFont());
        icon = IconFontSwing.buildIcon(FontAwesome.SEARCH, 24, new Color(0, 150, 0));
        jButtonSearchPatient = new javax.swing.JButton(icon);
        IconFontSwing.register(FontAwesome.getIconFont());
        icon = IconFontSwing.buildIcon(FontAwesome.CALENDAR_CHECK_O, 24, new Color(0, 150, 0));
        jButtonAddVisit = new javax.swing.JButton(icon);
        IconFontSwing.register(FontAwesome.getIconFont());
        icon = IconFontSwing.buildIcon(FontAwesome.HEARTBEAT, 24, new Color(0, 150, 0));
        jButtonCaptureVitals = new javax.swing.JButton(icon);
        IconFontSwing.register(FontAwesome.getIconFont());
        icon = IconFontSwing.buildIcon(FontAwesome.FLASK, 24, new Color(0, 150, 0));
        jButtonLaboratory = new javax.swing.JButton(icon);
        IconFontSwing.register(FontAwesome.getIconFont());
        icon = IconFontSwing.buildIcon(FontAwesome.MONEY, 24, new Color(0, 150, 0));
        jButtonBilling = new javax.swing.JButton(icon);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRegisterPatient.setText("Register Patient");
        jButtonRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterPatientActionPerformed(evt);
            }
        });

        jButtonSearchPatient.setText("Search Patient");
        jButtonSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchPatientActionPerformed(evt);
            }
        });

        jButtonAddVisit.setText("Add Visit");
        jButtonAddVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVisitActionPerformed(evt);
            }
        });

        jButtonCaptureVitals.setText("Capture Vitals");
        jButtonCaptureVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaptureVitalsActionPerformed(evt);
            }
        });

        jButtonLaboratory.setText("Laboratory");
        jButtonLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaboratoryActionPerformed(evt);
            }
        });

        jButtonBilling.setText("Billing");
        jButtonBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillingActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\usiu\\mis6030\\iclinic\\resources\\imgs\\logo02.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonRegisterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCaptureVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonLaboratory, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegisterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCaptureVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLaboratory, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterPatientActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Add();
    }//GEN-LAST:event_jButtonRegisterPatientActionPerformed

    private void jButtonSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchPatientActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Search();
    }//GEN-LAST:event_jButtonSearchPatientActionPerformed

    private void jButtonAddVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVisitActionPerformed
        // TODO add your handling code here:
        iclinic.controller.PatientController.Search();
    }//GEN-LAST:event_jButtonAddVisitActionPerformed

    private void jButtonCaptureVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaptureVitalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCaptureVitalsActionPerformed

    private void jButtonLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaboratoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLaboratoryActionPerformed

    private void jButtonBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainWindow().setVisible(true);
            }
        });
    

    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVisit;
    private javax.swing.JButton jButtonBilling;
    private javax.swing.JButton jButtonCaptureVitals;
    private javax.swing.JButton jButtonLaboratory;
    private javax.swing.JButton jButtonRegisterPatient;
    private javax.swing.JButton jButtonSearchPatient;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
